name: Assignment 1 Python Application Test with Github Actions from Cindy
on:
  schedule:
  - cron:  '0 3 * * SUN'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with: 
          python-version: "3.10"
          
      - name: install packages and dependencies
        run: |
          make install
      - name: lint with pylint
        run: |
          make lint
      - name: test with pytest
        run: |
          make test
      - name: format with black 
        run: |
          make format
      # - name: deploy the app
      #   run: |
      #     make deploy